### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by gac2117** [learn-co-curriculum/experiencing-html-lab#5]
I just noticed a few small issues while reading through.
First, there is a capitalization error. I think the "we" should be capitalized. 

> In the example, you see a list of songs. **we** see a list of songs. But a browser doesn't know what a "list" is.

> 

Also, these lines have typos:

> The `</li>` `li` list item closing tag
We would call this pair of opening and closing tags"an `li` tag"
> 

And in the instructions for creating an HTML list, it says to use `command + s` to save, but that's a Mac keyboard shortcut, and so to be fair, maybe the PC keyboard shortcut can also be added. 

And just thinking from a newbie point of view, when talking about the `httpserver`, a student might expect to see the same website address on their computer too, so maybe it can be specified like

> For our example, `httpserver` says: `Your server is running at 67.205.152.27:59976` but yours will be different.

I've seen other lessons in this curriculum where it's stated somewhat like that, so it was clear to understand.

**Comment by jenmyers** [comment]
All these issues have been resolved, thank you!
