### ISSUE TITLE
A Few Typos & Words Missing- Easy Fixes 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/experiencing-html-lab#6]
**1.. "yours" should be "your's"** 
ASIDE: For our example, our server is running at 67.205.152.27:59976 but keep in mind that yours could be different.

**2. "treat" should be "to treat"** 
ASIDE: If you've been following along closely, you might be wondering, if we didn't have a <ul> tag around our <li> items earlier, how did the browser know how treat those <li> as if they were in a <ul>
*******************
**3. Remove extra word "an" --"an more"** 
In upcoming lessons, we will learn additional tags which provide us an more ways to describe our content.
************
**4. Missing word "the" ("the idea")** 
It may not seem like we did much work, but idea of a method for "marking up" content and linking it is the foundation of the web. It's what made Tim Berners-Lee's reputation. And you just experienced Sir Tim's great insight. AWESOME.

**Comment by jenmyers** [comment]
Issues resolved. Thanks!
